rvm:
  - 2.0.0

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2
  - tar -xf phantomjs-1.7.0-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.7.0-linux-i686 /usr/local/phantomjs

env: RAILS_ENV=test
