rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - ree
  - jruby

script: bundle exec rspec spec

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

env: RAILS_ENV=test
