development:
  adapter: postgresql
  encoding: unicode
  database: easy_auth_development
  pool: 5
  username:
  password:
  min_messages: warning
test:
  adapter: postgresql
  encoding: unicode
  database: easy_auth_test
  pool: 5
<% if ENV['TRAVIS'] %>
  username: postgres
<% else %>
  username:
<% end %>
  password:
  min_messages: warning
